"$schema" = 'https://starship.rs/config-schema.json'

format = """
$battery\
$directory\
$custom\
$docker_context\
$env_var\
$jobs\
$status\
$os\
$container\
$cmd_duration\
$line_break\
$sudo\
$character
"""

right_format = """
$nix_shell\
$lua\
$nodejs\
$python\
$rust\
$package\
$time
"""

[[battery.display]]
style = 'bold red'
threshold = 20

[custom.jj]
format = "$output "
shell = ["jj-starship", "--jj-symbol", "  "]
when = "jj-starship detect"

[lua]
format = '[$symbol($version )]($style)  '
symbol = "  "

[nix_shell]
format = '[$symbol$state( \($name\))]($style)  '
symbol = " —"

[nodejs]
format = '[$symbol($version )]($style)  '

[package]
format = '[$symbol$version]($style)  '
style = "white"
symbol = "  "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)  '
symbol = "󰌠  "

[rust]
format = '[$symbol($version )]($style)  '
symbol = "  "

# [shell]
# disabled = false
# fish_indicator = "   "
# style = "cyan"

[sudo]
disabled = false
format = '[$symbol]($style)'
style = "#7e818b"
symbol = ' '

[time]
disabled = false
format = '[$time]($style) '
style = "#7e818b"
