"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$custom\
$docker_context\
$env_var\
$jobs\
$container\
$nix_shell\
$cmd_duration\
$fill\
$package\
$lua\
$nodejs\
$python\
$rust\
$battery\
$time\
$line_break\
$sudo\
$character
"""

# By using only the symbol for the format value, we can change the color
# of the percentage text along with the symbol.
[battery]
format = "$symbol "
unknown_symbol = '[󰂑 ---](fg:#f5c68f)'

[[battery.display]]
charging_symbol = '[󰂅 $percentage](fg:#96c065)'
discharging_symbol = '[󰁹 $percentage](fg:#5ebdea)'
threshold = 100

[[battery.display]]
charging_symbol = '[󰂋 $percentage](fg:#96c065)'
discharging_symbol = '[󰂂 $percentage](fg:#5ebdea)'
threshold = 90

[[battery.display]]
charging_symbol = '[󰂊 $percentage](fg:#96c065)'
discharging_symbol = '[󰂁 $percentage](fg:#5ebdea)'
threshold = 80

[[battery.display]]
charging_symbol = '[󰢞 $percentage](fg:#96c065)'
discharging_symbol = '[󰂀 $percentage](fg:#5ebdea)'
threshold = 70

[[battery.display]]
charging_symbol = '[󰂉 $percentage](fg:#96c065)'
discharging_symbol = "[󰁿 $percentage](fg:#5ebdea)"
threshold = 60

[[battery.display]]
charging_symbol = '[󰢝 $percentage](fg:#96c065)'
discharging_symbol = '[󰁾 $percentage](fg:#5ebdea)'
threshold = 50

[[battery.display]]
charging_symbol = '[󰂈 $percentage](fg:#96c065)'
discharging_symbol = '[󰁽 $percentage](fg:#5ebdea)'
threshold = 40

[[battery.display]]
charging_symbol = '[󰂇 $percentage](fg:#96c065)'
discharging_symbol = '[󰁼 $percentage](fg:#5ebdea)'
threshold = 30

[[battery.display]]
charging_symbol = '[󰂆 $percentage](fg:#96c065)'
discharging_symbol = '[󰁻 $percentage](fg:#f5c68f)'
threshold = 20

[[battery.display]]
charging_symbol = '[󰢜 $percentage](fg:#96c065)'
discharging_symbol = '[󰁺 $percentage](fg:#f46a80)'
threshold = 10

[custom.jj]
format = "$output "
shell = ["jj-starship", "--no-jj-prefix"]
when = "jj-starship detect"

[fill]
symbol = " "

[lua]
format = '[$symbol($version )]($style)  '
symbol = "  "

[nix_shell]
format = '[$symbol$state( \($name\))]($style)  '
symbol = "  "

[nodejs]
format = '[$symbol($version )]($style)  '
symbol = "  "

[package]
format = '[$symbol$version]($style)  '
style = "white"
symbol = "  "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)  '
symbol = "󰌠  "

[rust]
format = '[$symbol($version )]($style)  '
symbol = "  "

[sudo]
disabled = false
format = '[$symbol]($style)'
style = "#7e818b"
symbol = ' '

[time]
disabled = false
format = '[$time]($style) '
style = "#7e818b"
